### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by smallgirl6**
Hi 彭彭teacher.I am 芷瑩.
I have modifed my worl .
Could you kindly check it again ?
Thank you very much.

http://3.113.54.225:3000/api/attractions?page=1
http://3.113.54.225:3000/api/attractions?page=0&keyword=藝文館所
http://3.113.54.225:3000/api/attractions?page=0&keyword=北
http://3.113.54.225:3000/api/attraction/10
http://3.113.54.225:3000/api/categories

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
OK. Done.

It's better to re-request review in the same PR, so that we can trace history conversation.

**Comment by smallgirl6** [comment]
Thank you  彭彭teacher.
I saw you approved my changes.
just for confirmation, could I merge <code>develop</code> to <code>main</code> now?

**Comment by cwpeng** [comment]
Of course, you SHOULD merge to main after review approval.

**Comment by smallgirl6** [comment]
Ok.Thank you very.

**Pull request merged**
