### PR TITLE
2022-12-06 9:53

### PR DESCRIPTION
**Pull request by smallgirl6**
Hi 彭彭 teacher
I am 倪芷瑩
Sorry for the delay.
I have already finished the work.
Couldy you kindly check my work?
Thank you. 
http://3.113.54.225:3000/
http://3.113.54.225:3000/attraction/5

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Layout exceed screen width in middle size devices.
2. Style of text in attraction block in home page should keep align with design even if we add link to it.

**Comment by smallgirl6** [comment]
Hi 彭彭 teacher
I have already modified the work.
Couldy you kindly check my work again?
Thank you.
http://3.113.54.225:3000/
http://3.113.54.225:3000/attraction/5

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by smallgirl6** [comment]
Thank you 彭彭 teacher

**Pull request merged**
