### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by smallgirl6**
Hi 彭彭 teacher.
I am 倪芷瑩.
I have finished my work.
Could you kindly check my work?
Thank you very much.
http://3.113.54.225:3000/
http://3.113.54.225:3000/attraction/2
http://3.113.54.225:3000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your booking page shows previous attraction which should be replaced after we delete one. In our expactation, there should be empty after we delete booked attraction.

**Comment by smallgirl6** [comment]
Hi 彭彭 teacher.
I have modified my work.
Could you kindly check my work again?
Thank you very much.
http://3.113.54.225:3000/
http://3.113.54.225:3000/attraction/2
http://3.113.54.225:3000/booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done with two small issues:
1. Text color in footer should be white.
2. Add link to home page on website title.

**Comment by smallgirl6** [comment]
Thank you彭彭 teacher.
I have modified my work.
Could you kindly check my work again?
Thank you very much.
http://3.113.54.225:3000/
http://3.113.54.225:3000/attraction/2
http://3.113.54.225:3000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by smallgirl6** [comment]
Thank you 彭彭 teacher.

**Pull request merged**
