### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by smallgirl6**
Hi 彭彭teacher
I am 芷瑩.
Sorry for  the delay.
I have already finished my work.
Could you kindly check my work.
Thank you very much.
URL    http://3.113.54.225:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot get next page attractions if I search 藝文館所

**Comment by smallgirl6** [comment]
Hi 彭彭teacher
I modified my work.
Could you kindly check my work again?
Thank you very much.
URL http://3.113.54.225:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your server is getting down after some testings. Try to find out the root cause and fix it.

**Comment by smallgirl6** [comment]
Hi 彭彭teacher
I modified my work.
Could you kindly check my work again?
Thank you very much.
URL http://3.113.54.225:3000/

**Review by cwpeng — COMMENTED** [review]
Not work.

**Comment by smallgirl6** [comment]
Sorry  彭彭teacher.
I restarted it again.
Could you kindly check my work again?
Thank you very much.
URL http://3.113.54.225:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by smallgirl6** [comment]
Thank you.

**Pull request merged**
